### ISSUE TITLE
I think that I saved something to the sandbox and it continues to show up.  

### ISSUE THREAD

**Issue by m-gamao** [learn-co-curriculum/sinatra-from-scratch-readme#13]

**Comment by drakeltheryuujin** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum.

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
